//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetToolDatabaseEntities : DbContext
    {
        public AssetToolDatabaseEntities()
            : base("name=AssetToolDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAsset> tblAssets { get; set; }
        public DbSet<tblEvent> tblEvents { get; set; }
        public DbSet<tblEventSetting> tblEventSettings { get; set; }
        public DbSet<tblFragilityCurveSet> tblFragilityCurveSets { get; set; }
        public DbSet<tblLoadingLevel> tblLoadingLevels { get; set; }
        public DbSet<tblLoadingLocation> tblLoadingLocations { get; set; }
        public DbSet<tblLoadingScenario> tblLoadingScenarios { get; set; }
        public DbSet<tblRiskResult> tblRiskResults { get; set; }
        public DbSet<tblRiskRun> tblRiskRuns { get; set; }
        public DbSet<tlkpAssetType> tlkpAssetTypes { get; set; }
        public DbSet<tlkpConditionGrade> tlkpConditionGrades { get; set; }
        public DbSet<tlkpFragilityCurve> tlkpFragilityCurves { get; set; }
        public DbSet<tlkpImpactType> tlkpImpactTypes { get; set; }
    }
}
