//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsset
    {
        public tblAsset()
        {
            this.tblEventSettings = new HashSet<tblEventSetting>();
            this.tblRiskResults = new HashSet<tblRiskResult>();
        }
    
        public Nullable<int> ObjectID { get; set; }
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public string ConditionGrade { get; set; }
        public Nullable<float> AssetLength { get; set; }
        public Nullable<float> CrestLevel { get; set; }
        public Nullable<float> GroundLevel { get; set; }
        public Nullable<int> LoadingLocationID { get; set; }
    
        public virtual tlkpAssetType tlkpAssetType { get; set; }
        public virtual tlkpConditionGrade tlkpConditionGrade { get; set; }
        public virtual ICollection<tblEventSetting> tblEventSettings { get; set; }
        public virtual ICollection<tblRiskResult> tblRiskResults { get; set; }
    }
}
