//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFragilityCurveSet
    {
        public tblFragilityCurveSet()
        {
            this.tblRiskRuns = new HashSet<tblRiskRun>();
            this.tlkpFragilityCurves = new HashSet<tlkpFragilityCurve>();
        }
    
        public int FragilityCurveSetID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblRiskRun> tblRiskRuns { get; set; }
        public virtual ICollection<tlkpFragilityCurve> tlkpFragilityCurves { get; set; }
    }
}
