//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoadingLocation
    {
        public tblLoadingLocation()
        {
            this.tblLoadingLevels = new HashSet<tblLoadingLevel>();
        }
    
        public int LoadingLocationID { get; set; }
        public string LevelLoadingPointName { get; set; }
        public string Easting { get; set; }
        public string Northing { get; set; }
    
        public virtual ICollection<tblLoadingLevel> tblLoadingLevels { get; set; }
    }
}
