//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoadingScenario
    {
        public tblLoadingScenario()
        {
            this.tblLoadingLevels = new HashSet<tblLoadingLevel>();
            this.tblRiskRuns = new HashSet<tblRiskRun>();
        }
    
        public int LoadingScenarioID { get; set; }
        public string LoadingScenarioName { get; set; }
    
        public virtual ICollection<tblLoadingLevel> tblLoadingLevels { get; set; }
        public virtual ICollection<tblRiskRun> tblRiskRuns { get; set; }
    }
}
