//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRiskRun
    {
        public tblRiskRun()
        {
            this.tblRiskResults = new HashSet<tblRiskResult>();
        }
    
        public int RiskRunID { get; set; }
        public string Description { get; set; }
        public Nullable<int> FragilityCurveSetID { get; set; }
        public Nullable<int> LoadingScenarioID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<float> TotalRisk { get; set; }
    
        public virtual tblFragilityCurveSet tblFragilityCurveSet { get; set; }
        public virtual tblLoadingScenario tblLoadingScenario { get; set; }
        public virtual ICollection<tblRiskResult> tblRiskResults { get; set; }
    }
}
