//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRiskResult
    {
        public int ID { get; set; }
        public Nullable<int> RiskRunID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<float> RiskBestEstimate { get; set; }
        public Nullable<float> RiskLowerEstimate { get; set; }
        public Nullable<float> RiskUpperEstimate { get; set; }
        public Nullable<float> Contribution { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
        public virtual tblRiskRun tblRiskRun { get; set; }
    }
}
