//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetAssessmentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkpFragilityCurve
    {
        public int ObjectID { get; set; }
        public Nullable<int> FragilityCurveSetID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public string ConditionGrade { get; set; }
        public string X { get; set; }
        public Nullable<float> ProbabilityBestEstimate { get; set; }
        public Nullable<float> ProbabilityUpperEstimate { get; set; }
        public Nullable<float> ProbabilityLowerEstimate { get; set; }
    
        public virtual tblFragilityCurveSet tblFragilityCurveSet { get; set; }
        public virtual tlkpAssetType tlkpAssetType { get; set; }
        public virtual tlkpConditionGrade tlkpConditionGrade { get; set; }
    }
}
